package model;
// Generated Apr 14, 2015 8:31:57 PM by Hibernate Tools 3.6.0



/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta  implements java.io.Serializable {


     private int detalleFacturaId;
     private Componente componente;
     private Venta venta;
     private int cantidad;
     private double subTotal;
     private String descripcion;

    public DetalleVenta() {
    }

	
    public DetalleVenta(int detalleFacturaId, Componente componente, Venta venta, int cantidad, double subTotal) {
        this.detalleFacturaId = detalleFacturaId;
        this.componente = componente;
        this.venta = venta;
        this.cantidad = cantidad;
        this.subTotal = subTotal;
    }
    public DetalleVenta(int detalleFacturaId, Componente componente, Venta venta, int cantidad, double subTotal, String descripcion) {
       this.detalleFacturaId = detalleFacturaId;
       this.componente = componente;
       this.venta = venta;
       this.cantidad = cantidad;
       this.subTotal = subTotal;
       this.descripcion = descripcion;
    }
   
    public int getDetalleFacturaId() {
        return this.detalleFacturaId;
    }
    
    public void setDetalleFacturaId(int detalleFacturaId) {
        this.detalleFacturaId = detalleFacturaId;
    }
    public Componente getComponente() {
        return this.componente;
    }
    
    public void setComponente(Componente componente) {
        this.componente = componente;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(double subTotal) {
        this.subTotal = subTotal;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


