package model;
// Generated Apr 14, 2015 8:31:57 PM by Hibernate Tools 3.6.0



/**
 * Estados generated by hbm2java
 */
public class Estados  implements java.io.Serializable {


     private int estadoId;
     private String descripcion;

    public Estados() {
    }

	
    public Estados(int estadoId) {
        this.estadoId = estadoId;
    }
    public Estados(int estadoId, String descripcion) {
       this.estadoId = estadoId;
       this.descripcion = descripcion;
    }
   
    public int getEstadoId() {
        return this.estadoId;
    }
    
    public void setEstadoId(int estadoId) {
        this.estadoId = estadoId;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


