package model;
// Generated Apr 14, 2015 8:31:57 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int proveedorId;
     private String nombre;
     private String apellido;
     private String direccion;
     private String telefono;
     private String ci;
     private String codProveedor;
     private String dv;
     private String estado;
     private Set compras = new HashSet(0);
     private Set notaRemisions = new HashSet(0);
     private Set cuentases = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(int proveedorId) {
        this.proveedorId = proveedorId;
    }
    public Proveedor(int proveedorId, String nombre, String apellido, String direccion, String telefono, String ci, String codProveedor, String dv, String estado, Set compras, Set notaRemisions, Set cuentases) {
       this.proveedorId = proveedorId;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.ci = ci;
       this.codProveedor = codProveedor;
       this.dv = dv;
       this.estado = estado;
       this.compras = compras;
       this.notaRemisions = notaRemisions;
       this.cuentases = cuentases;
    }
   
    public int getProveedorId() {
        return this.proveedorId;
    }
    
    public void setProveedorId(int proveedorId) {
        this.proveedorId = proveedorId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public String getCodProveedor() {
        return this.codProveedor;
    }
    
    public void setCodProveedor(String codProveedor) {
        this.codProveedor = codProveedor;
    }
    public String getDv() {
        return this.dv;
    }
    
    public void setDv(String dv) {
        this.dv = dv;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getNotaRemisions() {
        return this.notaRemisions;
    }
    
    public void setNotaRemisions(Set notaRemisions) {
        this.notaRemisions = notaRemisions;
    }
    public Set getCuentases() {
        return this.cuentases;
    }
    
    public void setCuentases(Set cuentases) {
        this.cuentases = cuentases;
    }




}


