package model;
// Generated Apr 14, 2015 8:31:57 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int ventaId;
     private Cliente cliente;
     private int nroPrefijo;
     private int nroFactura;
     private Date fecha;
     private double precioTotal;
     private int cantidadTotal;
     private Double descuento;
     private Double iva;
     private Double precioExenta;
     private String pagoContado;
     private String estado;
     private String rucCi;
     private Integer factReferenciada;
     private char esFactura;
     private Date vencimiento;
     private Set detalleVentas = new HashSet(0);
     private Set pagoFacturas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(int ventaId, Cliente cliente, int nroPrefijo, int nroFactura, Date fecha, double precioTotal, int cantidadTotal, String pagoContado, String estado, String rucCi, char esFactura, Date vencimiento) {
        this.ventaId = ventaId;
        this.cliente = cliente;
        this.nroPrefijo = nroPrefijo;
        this.nroFactura = nroFactura;
        this.fecha = fecha;
        this.precioTotal = precioTotal;
        this.cantidadTotal = cantidadTotal;
        this.pagoContado = pagoContado;
        this.estado = estado;
        this.rucCi = rucCi;
        this.esFactura = esFactura;
        this.vencimiento = vencimiento;
    }
    public Venta(int ventaId, Cliente cliente, int nroPrefijo, int nroFactura, Date fecha, double precioTotal, int cantidadTotal, Double descuento, Double iva, Double precioExenta, String pagoContado, String estado, String rucCi, Integer factReferenciada, char esFactura, Date vencimiento, Set detalleVentas, Set pagoFacturas) {
       this.ventaId = ventaId;
       this.cliente = cliente;
       this.nroPrefijo = nroPrefijo;
       this.nroFactura = nroFactura;
       this.fecha = fecha;
       this.precioTotal = precioTotal;
       this.cantidadTotal = cantidadTotal;
       this.descuento = descuento;
       this.iva = iva;
       this.precioExenta = precioExenta;
       this.pagoContado = pagoContado;
       this.estado = estado;
       this.rucCi = rucCi;
       this.factReferenciada = factReferenciada;
       this.esFactura = esFactura;
       this.vencimiento = vencimiento;
       this.detalleVentas = detalleVentas;
       this.pagoFacturas = pagoFacturas;
    }
   
    public int getVentaId() {
        return this.ventaId;
    }
    
    public void setVentaId(int ventaId) {
        this.ventaId = ventaId;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public int getNroPrefijo() {
        return this.nroPrefijo;
    }
    
    public void setNroPrefijo(int nroPrefijo) {
        this.nroPrefijo = nroPrefijo;
    }
    public int getNroFactura() {
        return this.nroFactura;
    }
    
    public void setNroFactura(int nroFactura) {
        this.nroFactura = nroFactura;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public double getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(double precioTotal) {
        this.precioTotal = precioTotal;
    }
    public int getCantidadTotal() {
        return this.cantidadTotal;
    }
    
    public void setCantidadTotal(int cantidadTotal) {
        this.cantidadTotal = cantidadTotal;
    }
    public Double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Double descuento) {
        this.descuento = descuento;
    }
    public Double getIva() {
        return this.iva;
    }
    
    public void setIva(Double iva) {
        this.iva = iva;
    }
    public Double getPrecioExenta() {
        return this.precioExenta;
    }
    
    public void setPrecioExenta(Double precioExenta) {
        this.precioExenta = precioExenta;
    }
    public String getPagoContado() {
        return this.pagoContado;
    }
    
    public void setPagoContado(String pagoContado) {
        this.pagoContado = pagoContado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getRucCi() {
        return this.rucCi;
    }
    
    public void setRucCi(String rucCi) {
        this.rucCi = rucCi;
    }
    public Integer getFactReferenciada() {
        return this.factReferenciada;
    }
    
    public void setFactReferenciada(Integer factReferenciada) {
        this.factReferenciada = factReferenciada;
    }
    public char getEsFactura() {
        return this.esFactura;
    }
    
    public void setEsFactura(char esFactura) {
        this.esFactura = esFactura;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }
    public Set getPagoFacturas() {
        return this.pagoFacturas;
    }
    
    public void setPagoFacturas(Set pagoFacturas) {
        this.pagoFacturas = pagoFacturas;
    }




}


