package modelo;
// Generated Mar 11, 2015 2:13:18 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private int compraId;
     private Proveedor proveedor;
     private int nroPrefijo;
     private int nroFactura;
     private Date fecha;
     private Integer proyectoId;
     private Integer actividadId;
     private double precioTotal;
     private int cantidadTotal;
     private Double descuento;
     private Double iva;
     private Double precioExenta;
     private String pagoContado;
     private String estado;
     private String rucCi;
     private Integer factReferenciada;
     private char esFactura;
     private Date vencimiento;
     private Set pagoFacturas = new HashSet(0);
     private Set detalleCompras = new HashSet(0);

    public Compra() {
    }

	
    public Compra(int compraId, Proveedor proveedor, int nroPrefijo, int nroFactura, Date fecha, double precioTotal, int cantidadTotal, String pagoContado, String estado, String rucCi, char esFactura, Date vencimiento) {
        this.compraId = compraId;
        this.proveedor = proveedor;
        this.nroPrefijo = nroPrefijo;
        this.nroFactura = nroFactura;
        this.fecha = fecha;
        this.precioTotal = precioTotal;
        this.cantidadTotal = cantidadTotal;
        this.pagoContado = pagoContado;
        this.estado = estado;
        this.rucCi = rucCi;
        this.esFactura = esFactura;
        this.vencimiento = vencimiento;
    }
    public Compra(int compraId, Proveedor proveedor, int nroPrefijo, int nroFactura, Date fecha, Integer proyectoId, Integer actividadId, double precioTotal, int cantidadTotal, Double descuento, Double iva, Double precioExenta, String pagoContado, String estado, String rucCi, Integer factReferenciada, char esFactura, Date vencimiento, Set pagoFacturas, Set detalleCompras) {
       this.compraId = compraId;
       this.proveedor = proveedor;
       this.nroPrefijo = nroPrefijo;
       this.nroFactura = nroFactura;
       this.fecha = fecha;
       this.proyectoId = proyectoId;
       this.actividadId = actividadId;
       this.precioTotal = precioTotal;
       this.cantidadTotal = cantidadTotal;
       this.descuento = descuento;
       this.iva = iva;
       this.precioExenta = precioExenta;
       this.pagoContado = pagoContado;
       this.estado = estado;
       this.rucCi = rucCi;
       this.factReferenciada = factReferenciada;
       this.esFactura = esFactura;
       this.vencimiento = vencimiento;
       this.pagoFacturas = pagoFacturas;
       this.detalleCompras = detalleCompras;
    }
   
    public int getCompraId() {
        return this.compraId;
    }
    
    public void setCompraId(int compraId) {
        this.compraId = compraId;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public int getNroPrefijo() {
        return this.nroPrefijo;
    }
    
    public void setNroPrefijo(int nroPrefijo) {
        this.nroPrefijo = nroPrefijo;
    }
    public int getNroFactura() {
        return this.nroFactura;
    }
    
    public void setNroFactura(int nroFactura) {
        this.nroFactura = nroFactura;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getProyectoId() {
        return this.proyectoId;
    }
    
    public void setProyectoId(Integer proyectoId) {
        this.proyectoId = proyectoId;
    }
    public Integer getActividadId() {
        return this.actividadId;
    }
    
    public void setActividadId(Integer actividadId) {
        this.actividadId = actividadId;
    }
    public double getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(double precioTotal) {
        this.precioTotal = precioTotal;
    }
    public int getCantidadTotal() {
        return this.cantidadTotal;
    }
    
    public void setCantidadTotal(int cantidadTotal) {
        this.cantidadTotal = cantidadTotal;
    }
    public Double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Double descuento) {
        this.descuento = descuento;
    }
    public Double getIva() {
        return this.iva;
    }
    
    public void setIva(Double iva) {
        this.iva = iva;
    }
    public Double getPrecioExenta() {
        return this.precioExenta;
    }
    
    public void setPrecioExenta(Double precioExenta) {
        this.precioExenta = precioExenta;
    }
    public String getPagoContado() {
        return this.pagoContado;
    }
    
    public void setPagoContado(String pagoContado) {
        this.pagoContado = pagoContado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getRucCi() {
        return this.rucCi;
    }
    
    public void setRucCi(String rucCi) {
        this.rucCi = rucCi;
    }
    public Integer getFactReferenciada() {
        return this.factReferenciada;
    }
    
    public void setFactReferenciada(Integer factReferenciada) {
        this.factReferenciada = factReferenciada;
    }
    public char getEsFactura() {
        return this.esFactura;
    }
    
    public void setEsFactura(char esFactura) {
        this.esFactura = esFactura;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }
    public Set getPagoFacturas() {
        return this.pagoFacturas;
    }
    
    public void setPagoFacturas(Set pagoFacturas) {
        this.pagoFacturas = pagoFacturas;
    }
    public Set getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set detalleCompras) {
        this.detalleCompras = detalleCompras;
    }




}


