package modelo;
// Generated Mar 11, 2015 2:13:18 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NotaRemision generated by hbm2java
 */
public class NotaRemision  implements java.io.Serializable {


     private int remisionId;
     private Proveedor proveedor;
     private int nroRemito;
     private int nroPrefijo;
     private String codProyecto;
     private String estado;
     private String razonSocial;
     private String rucCi;
     private String puntoPartida;
     private String puntoLlegada;
     private Date fechaInicio;
     private Date fechaFin;
     private Set detalleRemisions = new HashSet(0);

    public NotaRemision() {
    }

	
    public NotaRemision(int remisionId, Proveedor proveedor, int nroRemito, int nroPrefijo, String codProyecto, String estado, String razonSocial, String rucCi, String puntoPartida, String puntoLlegada, Date fechaInicio, Date fechaFin) {
        this.remisionId = remisionId;
        this.proveedor = proveedor;
        this.nroRemito = nroRemito;
        this.nroPrefijo = nroPrefijo;
        this.codProyecto = codProyecto;
        this.estado = estado;
        this.razonSocial = razonSocial;
        this.rucCi = rucCi;
        this.puntoPartida = puntoPartida;
        this.puntoLlegada = puntoLlegada;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }
    public NotaRemision(int remisionId, Proveedor proveedor, int nroRemito, int nroPrefijo, String codProyecto, String estado, String razonSocial, String rucCi, String puntoPartida, String puntoLlegada, Date fechaInicio, Date fechaFin, Set detalleRemisions) {
       this.remisionId = remisionId;
       this.proveedor = proveedor;
       this.nroRemito = nroRemito;
       this.nroPrefijo = nroPrefijo;
       this.codProyecto = codProyecto;
       this.estado = estado;
       this.razonSocial = razonSocial;
       this.rucCi = rucCi;
       this.puntoPartida = puntoPartida;
       this.puntoLlegada = puntoLlegada;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.detalleRemisions = detalleRemisions;
    }
   
    public int getRemisionId() {
        return this.remisionId;
    }
    
    public void setRemisionId(int remisionId) {
        this.remisionId = remisionId;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public int getNroRemito() {
        return this.nroRemito;
    }
    
    public void setNroRemito(int nroRemito) {
        this.nroRemito = nroRemito;
    }
    public int getNroPrefijo() {
        return this.nroPrefijo;
    }
    
    public void setNroPrefijo(int nroPrefijo) {
        this.nroPrefijo = nroPrefijo;
    }
    public String getCodProyecto() {
        return this.codProyecto;
    }
    
    public void setCodProyecto(String codProyecto) {
        this.codProyecto = codProyecto;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getRucCi() {
        return this.rucCi;
    }
    
    public void setRucCi(String rucCi) {
        this.rucCi = rucCi;
    }
    public String getPuntoPartida() {
        return this.puntoPartida;
    }
    
    public void setPuntoPartida(String puntoPartida) {
        this.puntoPartida = puntoPartida;
    }
    public String getPuntoLlegada() {
        return this.puntoLlegada;
    }
    
    public void setPuntoLlegada(String puntoLlegada) {
        this.puntoLlegada = puntoLlegada;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Set getDetalleRemisions() {
        return this.detalleRemisions;
    }
    
    public void setDetalleRemisions(Set detalleRemisions) {
        this.detalleRemisions = detalleRemisions;
    }




}


