package modelo;
// Generated Mar 11, 2015 2:13:18 PM by Hibernate Tools 3.6.0



/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private int stockId;
     private Componente componente;
     private Integer idAdministrador;
     private int existencia;

    public Stock() {
    }

	
    public Stock(int stockId, Componente componente, int existencia) {
        this.stockId = stockId;
        this.componente = componente;
        this.existencia = existencia;
    }
    public Stock(int stockId, Componente componente, Integer idAdministrador, int existencia) {
       this.stockId = stockId;
       this.componente = componente;
       this.idAdministrador = idAdministrador;
       this.existencia = existencia;
    }
   
    public int getStockId() {
        return this.stockId;
    }
    
    public void setStockId(int stockId) {
        this.stockId = stockId;
    }
    public Componente getComponente() {
        return this.componente;
    }
    
    public void setComponente(Componente componente) {
        this.componente = componente;
    }
    public Integer getIdAdministrador() {
        return this.idAdministrador;
    }
    
    public void setIdAdministrador(Integer idAdministrador) {
        this.idAdministrador = idAdministrador;
    }
    public int getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(int existencia) {
        this.existencia = existencia;
    }




}


