package modelo;
// Generated Mar 11, 2015 2:13:18 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int clienteId;
     private String nombre;
     private String apellido;
     private String direccion;
     private String telefono;
     private String rucCi;
     private String estado;
     private Set cuentases = new HashSet(0);
     private Set ventas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int clienteId, String nombre, String rucCi, String estado) {
        this.clienteId = clienteId;
        this.nombre = nombre;
        this.rucCi = rucCi;
        this.estado = estado;
    }
    public Cliente(int clienteId, String nombre, String apellido, String direccion, String telefono, String rucCi, String estado, Set cuentases, Set ventas) {
       this.clienteId = clienteId;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.rucCi = rucCi;
       this.estado = estado;
       this.cuentases = cuentases;
       this.ventas = ventas;
    }
   
    public int getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(int clienteId) {
        this.clienteId = clienteId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getRucCi() {
        return this.rucCi;
    }
    
    public void setRucCi(String rucCi) {
        this.rucCi = rucCi;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getCuentases() {
        return this.cuentases;
    }
    
    public void setCuentases(Set cuentases) {
        this.cuentases = cuentases;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


