package modelo;
// Generated Mar 11, 2015 2:13:18 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int porveedorId;
     private String nombre;
     private String apellido;
     private String direccion;
     private String telefono;
     private String rucCi;
     private String estado;
     private String codProveedor;
     private Set notaRemisions = new HashSet(0);
     private Set cuentases = new HashSet(0);
     private Set compras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(int porveedorId, String nombre, String rucCi, String estado, String codProveedor) {
        this.porveedorId = porveedorId;
        this.nombre = nombre;
        this.rucCi = rucCi;
        this.estado = estado;
        this.codProveedor = codProveedor;
    }
    public Proveedor(int porveedorId, String nombre, String apellido, String direccion, String telefono, String rucCi, String estado, String codProveedor, Set notaRemisions, Set cuentases, Set compras) {
       this.porveedorId = porveedorId;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.rucCi = rucCi;
       this.estado = estado;
       this.codProveedor = codProveedor;
       this.notaRemisions = notaRemisions;
       this.cuentases = cuentases;
       this.compras = compras;
    }
   
    public int getPorveedorId() {
        return this.porveedorId;
    }
    
    public void setPorveedorId(int porveedorId) {
        this.porveedorId = porveedorId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getRucCi() {
        return this.rucCi;
    }
    
    public void setRucCi(String rucCi) {
        this.rucCi = rucCi;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCodProveedor() {
        return this.codProveedor;
    }
    
    public void setCodProveedor(String codProveedor) {
        this.codProveedor = codProveedor;
    }
    public Set getNotaRemisions() {
        return this.notaRemisions;
    }
    
    public void setNotaRemisions(Set notaRemisions) {
        this.notaRemisions = notaRemisions;
    }
    public Set getCuentases() {
        return this.cuentases;
    }
    
    public void setCuentases(Set cuentases) {
        this.cuentases = cuentases;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


