package model;
// Generated Apr 14, 2015 8:31:57 PM by Hibernate Tools 3.6.0



/**
 * DetalleCompra generated by hbm2java
 */
public class DetalleCompra  implements java.io.Serializable {


     private int detalleCompraId;
     private Componente componente;
     private Compra compra;
     private int cantidad;
     private double subTotal;
     private String descripcion;
     private String codigo;
     private double precioExcenta;

    public DetalleCompra() {
    }

	
    public DetalleCompra(int detalleCompraId, Componente componente, Compra compra, int cantidad, double subTotal, String codigo, double precioExcenta) {
        this.detalleCompraId = detalleCompraId;
        this.componente = componente;
        this.compra = compra;
        this.cantidad = cantidad;
        this.subTotal = subTotal;
        this.codigo = codigo;
        this.precioExcenta = precioExcenta;
    }
    public DetalleCompra(int detalleCompraId, Componente componente, Compra compra, int cantidad, double subTotal, String descripcion, String codigo, double precioExcenta) {
       this.detalleCompraId = detalleCompraId;
       this.componente = componente;
       this.compra = compra;
       this.cantidad = cantidad;
       this.subTotal = subTotal;
       this.descripcion = descripcion;
       this.codigo = codigo;
       this.precioExcenta = precioExcenta;
    }
   
    public int getDetalleCompraId() {
        return this.detalleCompraId;
    }
    
    public void setDetalleCompraId(int detalleCompraId) {
        this.detalleCompraId = detalleCompraId;
    }
    public Componente getComponente() {
        return this.componente;
    }
    
    public void setComponente(Componente componente) {
        this.componente = componente;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(double subTotal) {
        this.subTotal = subTotal;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public double getPrecioExcenta() {
        return this.precioExcenta;
    }
    
    public void setPrecioExcenta(double precioExcenta) {
        this.precioExcenta = precioExcenta;
    }




}


