package model;
// Generated Apr 14, 2015 8:31:57 PM by Hibernate Tools 3.6.0



/**
 * PagosCombo generated by hbm2java
 */
public class PagosCombo  implements java.io.Serializable {


     private int idPago;
     private String nombre;

    public PagosCombo() {
    }

	
    public PagosCombo(int idPago) {
        this.idPago = idPago;
    }
    public PagosCombo(int idPago, String nombre) {
       this.idPago = idPago;
       this.nombre = nombre;
    }
   
    public int getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(int idPago) {
        this.idPago = idPago;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


